### PR TITLE
Move sorting parameter in database query APIs to body request

### LINKED ISSUE #24: Pagination fails due to start cursor encoded as query parameter
The Notion [documentation](https://developers.notion.com/reference/post-database-query) shows that `START_CURSOR` is encoded in the request body, but here it's added as a URL parameter, which as of the API version `2021-08-16` responds with a validation error.

`https://api.notion.com/v1/databases/{DATABASE_ID}/query?start_cursor={PAGE_ID}`

```
{
  "object": "error",
  "status": 400,
  "code": "validation_error",
  "message": "query failed validation: query.start_cursor should be not present, instead was `\"e8635964-722c-4aed-a33d-ac3709280c99\"`."
}
```

This behaviour can be reproduced by setting up the request in manually (cUrl/Postman/Insomnia), and then changing this to a JSON body request.

It looks as though the `START_CURSOR` should be removed from `NotionService.kt`, and encoded with a `@SerialName` annotation in the `ApiDatabaseQuery` data class. There may also be other request body classes that need updating as well.

### PR DESCRIPTION
**Pull request by ashdavies**
Resolves #24

### CODE REVIEW

File: library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt [hunk 1]
```diff
@@ -218,17 +217,15 @@ internal class NotionService(private val httpClient: HttpClient) {
...
+    suspend fun searchPages(parameters: ApiSearchParameters): ApiResultPage<ApiPage> {
         return httpClient.post("$BASE_URL/$SEARCH") {
-            if (startCursor != null) parameter(START_CURSOR, startCursor)
             contentType(ContentType.Application.Json)
             body = parameters
         }
     }
 
-    suspend fun searchDatabases(parameters: ApiSearchParameters, startCursor: String?): ApiResultPage<ApiDatabase> {
+    suspend fun searchDatabases(parameters: ApiSearchParameters): ApiResultPage<ApiDatabase> {
```
Comment (ashdavies) [inline library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt:227]: This has the same implementation as `searchPages`, could it be collapsed to just `search`?
Or at least alias to a single implementation?

Comment (BoD) [reply library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt:227]: You are totally right, let's have only one named `search` 👍

File: library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/database/query/ApiDatabaseQuery.kt [hunk 2]
```diff
@@ -25,13 +25,15 @@
...
 import kotlinx.serialization.Serializable
 
 /**
  * See [Reference](https://developers.notion.com/reference/post-database-query).
  */
 @Serializable
 internal data class ApiDatabaseQuery(
-    val filter: ApiDatabaseQueryFilters? = null,
-    val sorts: List<ApiDatabaseQuerySort>? = null,
+    @SerialName("filter") val filter: ApiDatabaseQueryFilters? = null,
```
Comment (BoD) [inline library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/database/query/ApiDatabaseQuery.kt:36]: I see how using `@SerialName("filter")` is probably cleaner, but I made the (possibly regrettable) choice early on to name the properties in Api models with the corresponding json name. For consistency, I would rather not add them in this one. 

(If you're motivated, maybe they could be all added in a separate PR? 😁)

File: library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/search/ApiSearchParametersConverter.kt [hunk 3]
```diff
@@ -29,29 +29,22 @@ import org.jraf.klibnotion.internal.api.model.ApiConverter
...
-        val query = model.first
-        val sort = model.second
-        val type = model.third
-
+    ApiConverter<ApiSearchParameters, SearchParameters>() {
+    override fun modelToApi(model: SearchParameters): ApiSearchParameters {
         return ApiSearchParameters(
-            query = query,
-            sort = sort?.let {
+            query = model.query,
```
Comment (BoD) [inline library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/search/ApiSearchParametersConverter.kt:35]: We should also have `startCursor = model.startCursor,` here, right?

File: library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/database/query/ApiDatabaseQuery.kt (hunk 2 above)
Comment (ashdavies) [reply library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/database/query/ApiDatabaseQuery.kt:36]: Haha, then sure I'll update them to lower_case, consistency is more important 😉

File: library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/search/ApiSearchParametersConverter.kt (hunk 3 above)
Comment (ashdavies) [reply library/src/commonMain/kotlin/org/jraf/klibnotion/internal/api/model/search/ApiSearchParametersConverter.kt:35]: Good catch!

File: library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt (hunk 1 above)
Comment (ashdavies) [reply library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt:227]: I'll create a separate PR

Comment (ashdavies) [reply library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt:227]: Whilst the API is the same, the API response is encoded differently here, so we should think about merging the expected API response, especially since the API might respond with either a page or a database, which could cause a deserialisation failure.

Comment (BoD) [reply library/src/commonMain/kotlin/org/jraf/klibnotion/internal/client/NotionService.kt:227]: Ah you're right :) Oh well!

**Review by BoD — APPROVED** [review]
Thanks a lot for this! 🙏
